keyword: blog 
favicon: /css/images/favicon.ico

excerpt_link: Read more

menu:
 Home: /
 Tags: /tags/
 Archives: /archives/
#  Projects: /project/
 About: /about/

# highlight
highlight:
  tomorrow

# catalog
catalog: true

# donate
donate: false

# qrcode
qrcode: false

# comment
# you can set gitment, uyan or disqus

comment: disqus

# gitment config
# gitment_owner: yanm1ng
# gitment_repo: yanm1ng.github.io
# gitment_oauth_id: 0f87e490e00ee3fd87ef
# gitment_oauth_secret: 4a9d2b148e7971c2201ad12131ce8bf8159ccd2e

# uyan config
# if you want to use uyan as your blog comment, plz remove/comment out gitment config
# baidu_id: 

# disqus config
disqus_shortname: shawnlin

about: 
  banner: https://health.columbia.edu/sites/default/files/styles/cu_crop/public/content/Kevin%20Butler.jpg
  avatar: /css/images/avatar.jpg
  description: "Personally I'm always ready to learn, although I do not always like being taught.  - Winston Churchill"
  github_username: shawnlinxl 
  linkedin_username: xiaolianglin

# MathJax Support
mathjax:
  enable: true
  per_page: false
  cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML